### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [owenstranathan/owiewestside.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by owenstranathan** [comment]
Hey thanks! I added the license. I also have a pipenv plugin (which I prefer to the one oh-my-zsh adopted) if your interested. https://github.com/owenstranathan/pipenv.zsh

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/752

Looks like I already added your pipenv before I got strict about only adding things with licenses :-)
